### ISSUE TITLE
Improper alignment of boxplots in facets

### ISSUE THREAD

**Issue by ukkonen** [ropensci/plotly#697]
Hi,
first of all, thanks for a great package! 
I have spent some time with it recently and I think that I have found a bug. If I use boxplots and facets, the boxplots in the upper facet are on the left side of the category while the boxplots in the bottom facet are on the right side of the category, while I believe that they should be aligned in the middle. Picture tells more than thousands words, so see bellow...

you can get it with the following code:
```
library(ggplot2)
library(plotly)

data.1 <- diamonds
data.1$set <- "set1"

data.2 <- data.1
data.2$set <- "set2"

my.data <- rbind(data.1, data.2)

p <- ggplot(my.data, aes(x=cut, y=price, fill= clarity))+
  geom_boxplot()+
  facet_grid(set ~ .)

ggplotly(p)%>%
  layout(boxmode = "group")
```

![boxplots](https://cloud.githubusercontent.com/assets/21320427/18067525/79eb976a-6e3d-11e6-9545-42d6f78e17e3.png)

**Comment by Michelle-Muha** [comment]
I am experiencing the same / similar problem with facet_wrap.  If I plot a single facet, the plot looks great

```
p1 <- ggplot(diamonds[diamonds$color == "D",], aes(x=cut, y=price, fill= clarity))+
    geom_boxplot()+
    facet_wrap(~color, scales="free", ncol=1)
  
ggplotly(p1)%>%
    layout(boxmode = "group")
```

However, if I have several facets, the boxes become so thin they are imperceptible

```
p2 <- ggplot(diamonds, aes(x=cut, y=price, fill= clarity))+
    geom_boxplot()+
    facet_wrap(~color, scales="free", ncol=1)
  
ggplotly(p2, height=2000 )%>%
    layout(boxmode = "group")
```

**Comment by qztseng** [comment]
I have also encountered such issue with plotting boxplots with facets, either the boxes were stacked over each other, or they became too narrow:

Correct plot with ggplot:
```r
g <- ggplot(ex, aes(x=Version, y=Weight, color=Lot))+
  geom_boxplot(outlier.shape = NA)+
  geom_point(position=position_jitterdodge(jitter.width=NULL, jitter.height=0, dodge.width=0.75)) +
  theme(axis.text.x = element_text(angle=45, hjust=1))+
  scale_y_continuous("Weight", breaks = pretty_breaks())+
  facet_wrap(~Model)
g
```
![ggplot](https://cloud.githubusercontent.com/assets/17316611/22870952/63ba8068-f1e7-11e6-934f-cc644a49901e.png)
Plot the same thing with ggplotly (boxes of different group got stacked together):
![ggplotly](https://cloud.githubusercontent.com/assets/17316611/22870965/8428b37e-f1e7-11e6-902b-bf2f02bf85a2.png)
Plot with ggplotly adding boxmode argument (boxes became too narrow):
```r
ggplotly(g) %>% layout(boxmode = "group")
```
![ggplotly2](https://cloud.githubusercontent.com/assets/17316611/22870981/b4a5a8fe-f1e7-11e6-92d6-6a0323a6c58d.png)

**Comment by cpsievert** [comment]
These are all different issues:

* https://github.com/ropensci/plotly/issues/697#issue-173873355 doesn't seem to be a problem anymore

* https://github.com/ropensci/plotly/issues/697#issuecomment-267406661 and https://github.com/ropensci/plotly/issues/697#issuecomment-279292247 can be partially solved by making the plot wider and using `layout.boxgroupgap`.

Chalking this up as further evidence for https://github.com/ropensci/plotly/issues/706#issuecomment-292357273

**Comment by sockchinglow** [comment]
I'm a little late to the game, but maybe this will help someone. I had a similar issue to @LukasHebing (single box per row/x-point) and found that using the parameter `boxmode` worked to get the category columns aligned.

I'm still not 100% sure why this happens, but I strongly suspect it's an implicit assumption about the data structure combination with color/facet_col/facet_row/x.

## Example solution

Given the following data sample
![image](https://github.com/plotly/plotly.R/assets/16003056/3c100513-1020-453f-8eb7-4e4e72cf3182)

I would get the following results with the boxmode not specified:

```python3
# Plot figure (misaligned)
px.box(
    data,
    x='col',
    y='value',
    facet_row='row',
    color='group',
    # boxmode='overlay',
    width=500, height=300
)
```

![image](https://github.com/plotly/plotly.R/assets/16003056/98e9c8cd-94c7-4144-af38-a7080af5784f)

And with the boxmode set to `overlay`:

```python3
# Plot figure (aligned)
px.box(
    data,
    x='col',
    y='value',
    facet_row='row',
    color='group',
    boxmode='overlay',
    width=500, height=300
)
```

![image](https://github.com/plotly/plotly.R/assets/16003056/cad2e5df-ac77-4962-9405-ae6565c1c0d1)

However, if you have >1 box per category, this would cause the boxes to overlap (which is precisely what you set with that boxmode). Instead, using `boxmode='group'` should work.
