### ISSUE TITLE
dynamicTicks = TRUE for categorical axis

### ISSUE THREAD

**Issue by stanstrup** [ropensci/plotly#860]
See the following example.
When you add `dynamicTicks = TRUE` The date is not converted properly on the x-axis.

```
library("reshape2")
library("ggplot2")
library("plotly")

test_data <-
  data.frame(
    var0 = 100 + c(0, cumsum(runif(49, -20, 20))),
    var1 = 150 + c(0, cumsum(runif(49, -10, 10))),
    date = seq(as.Date("2002-01-01"), by="1 month", length.out=100)
  )


test_data_long <- melt(test_data, id="date")  # convert to long format

ggplot(data=test_data_long,
       aes(x=date, y=value, colour=variable)) +
       geom_line()

ggplotly(dynamicTicks = TRUE)
```

**Comment by lgaliano** [comment]
The issue is also seen with categorical x axis:
```r
library("ggplot2")
library("plotly")
ggplotly(ggplot(iris, aes(x=Species, y=Sepal.Length))+geom_point(), dynamicTicks = T)
```

**Comment by stanstrup** [comment]
And modified axis labels e.g.:
`scale_y_continuous(labels = percent)`

**Comment by cpsievert** [comment]
This is now fixed for dates, but still somewhat broken for categorical axes

**Comment by stanstrup** [comment]
This was solved for dates but not for POSIXct.

```
library("reshape2")
library("ggplot2")
library("plotly")

test_data <-
  data.frame(
    var0 = 100 + c(0, cumsum(runif(49, -20, 20))),
    var1 = 150 + c(0, cumsum(runif(49, -10, 10))),
    date = seq(as.Date("2002-01-01"), by="1 month", length.out=100) %>% as.POSIXct()
  )


test_data_long <- melt(test_data, id="date")  # convert to long format

ggplot(data=test_data_long,
       aes(x=date, y=value, colour=variable)) +
       geom_line()

ggplotly(dynamicTicks = TRUE)
```

![image](https://cloud.githubusercontent.com/assets/4532682/23955581/a0a8bbf0-099a-11e7-9b39-83fa4c625f2b.png)


Do you want a separate issue opened?

**Comment by cpsievert** [comment]
Ahh, thanks I see the issue...fix coming up

**Comment by stanstrup** [comment]
I am sorry but it is still not exactly right. We now start from 1970 somehow. But that is regardless of `dynamicTicks`.


```
library("reshape2")
library("ggplot2")
library("plotly")

test_data <-
  data.frame(
    var0 = 100 + c(0, cumsum(runif(49, -20, 20))),
    var1 = 150 + c(0, cumsum(runif(49, -10, 10))),
    date = seq(as.Date("2002-01-01"), by="1 month", length.out=100) %>% as.POSIXct()
  )


test_data_long <- melt(test_data, id="date")  # convert to long format

p <- ggplot(data=test_data_long,
       aes(x=date, y=value, colour=variable)) +
       geom_line()
```

![image](https://cloud.githubusercontent.com/assets/4532682/24038427/9b8f53e6-0b01-11e7-9096-67d7440b48f6.png)

```
pp <- ggplotly(p, dynamicTicks = TRUE)

pp$x$layout$margin$l <- pp$x$layout$margin$l + 30 # avoid cut axis titles
pp$x$layout$margin$b <- pp$x$layout$margin$b + 30
```

![image](https://cloud.githubusercontent.com/assets/4532682/24038461/c907aad0-0b01-11e7-892f-8349b19bf088.png)

**Comment by cpsievert** [comment]
Thanks; good thing someone is paying close attention 😉

**Comment by fruce-ki** [comment]
`Error in tickvals - val : non-numeric argument to binary operator`

Is it possible to have dynamic ticks for the (numeric) Y-axis when the X-axis is categorical (meaning string/factor values, not dates -- ticks should not be changed on the X-axis)?

**Comment by StephanSJ** [comment]
It seems that dynamicTicks=TRUE in ggplotly is working for categorical data  only when the plot is not faceted. Is there a reason for that or is this part of the bug you were working on here?

`p1 <- ggplot(mtcars) + 
  geom_line(aes(x=as.factor(hp), y=mpg, group=1))


p2 <- ggplot(mtcars) + 
      geom_line(aes(x=as.factor(hp), y=mpg, group=1)) +
      facet_wrap(vars(gear))

#non faceted plot works
ggplotly(p1, dynamicTicks = TRUE)

faceted plot does not work
ggplotly(p2, dynamicTicks = TRUE)`
